import Head from "next/head";
import BasicLayout from "../layouts/BasicLayout";
// import SectionPlates from "../components/SectionPlates";
// import { useHomeClient } from "../hooks/useHomeClient";

export default function Home() {
  // const { title1, title2, promoPlates, popuPlates } = useHomeClient();

  return (
    <BasicLayout>
      <Head>
        <title>Inicio | Central Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* {title1 && promoPlates?.length !== 0 && (
          <SectionPlates title={title1} plates={promoPlates} />
        )}
        {title2 && popuPlates?.length !== 0 && (
          <SectionPlates title={title2} plates={popuPlates} />
        )} */}
        aqui todo el index
      </main>
    </BasicLayout>
  );
}
