import Head from "next/head";
import DefaultLoader from "../components/DefaultLoader";
import PopularePlates from "../components/PopularPlates";
import PromotionPlates from "../components/PromotionPlates";
import { useData } from "../hooks/useData";

export default function Home() {
  const { data } = useData();

  if (!data) return <DefaultLoader />;

  return (
    <>
      <Head>
        <title>Inicio | Central Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data?.promotionPlates && <PromotionPlates data={data} />}
        {data?.popularPlates && <PopularePlates data={data} />}
      </main>
    </>
  );
}
