import Head from "next/head";
import PopularePlates from "../components/PopularPlates";
import PromotionPlates from "../components/PromotionPlates";
import { useData } from "../hooks/useData";
import BasicLayout from "../layouts/BasicLayout";
// import SectionPlates from "../components/SectionPlates";
// import { useHomeClient } from "../hooks/useHomeClient";

export default function Home() {
  // const { title1, title2, promoPlates, popuPlates } = useHomeClient();
  const { data } = useData();

  return (
    <BasicLayout>
      <Head>
        <title>Inicio | Central Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data?.promotionPlates && <PromotionPlates data={data} />}
        {data?.popularPlates && <PopularePlates data={data} />}
      </main>
    </BasicLayout>
  );
}
